version: '3.7'

services:
  postgres-tourplaner:
    image: postgres:alpine
    container_name: postgres-tourplaner
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PW}"
      POSTGRES_DB: "${DB_NAME}"
